### ISSUE TITLE
query - appeal solved issue

### ISSUE THREAD

**Issue by rvsp** [zen-class/zen-platform#15]
![image](https://user-images.githubusercontent.com/21954626/129394988-ec99ec73-82f6-499b-97e8-b449dbeafdbe.png)
![image](https://user-images.githubusercontent.com/21954626/129394995-580ce3f6-66ff-4b10-8748-d1fec61c4749.png)

in student side am able to do multiple appeal soled and in other side last message is shown

**Comment by thecoffeedev** [comment]
@rvsp, I think we have discussed this, if we are good, please close this issue.

**Comment by rvsp** [comment]
As we discussed for flow redesign, am closing this.
