### ISSUE TITLE
query creation - user

### ISSUE THREAD

**Issue by rvsp** [zen-class/zen-platform#16]
once the user is a closed query but on the mentor side, he's able to send messages for the same query

message view on student side
![image](https://user-images.githubusercontent.com/21954626/129395716-5b5cc588-aeb6-4f0c-b6f2-52d537d71b34.png)

when a student tries to create a new query it shows action pending
![image](https://user-images.githubusercontent.com/21954626/129395897-518f66c2-6011-4150-81a3-826542165106.png)

**Comment by thecoffeedev** [comment]
@rvsp, Neither student nor mentor can chat or reply to a query that is closed. please verify that it is in Live as well.
The action pending will be there if the student is not replied to his mentor or there is any resolved query.

**Comment by thecoffeedev** [comment]
@rvsp, Please verify and close this query.

**Comment by rvsp** [comment]
@thecoffeedev as we planned to redesign the flow, am closing this
