### ISSUE TITLE
password confirm mail

### ISSUE THREAD

**Issue by rvsp** [zen-class/zen-platform#2]
image in password confirm is broken
![image](https://user-images.githubusercontent.com/21954626/129070671-2912bb72-c23f-469e-a0c6-0b8455a1741c.png)

**Comment by Varghese1987** [comment]
Images in all emails updated, New User creation, Password created acknowledgment mail, student creation, new query and pick a query

**Comment by rvsp** [comment]
@Varghese1987 still shows mail with a broken image.
![image](https://user-images.githubusercontent.com/21954626/130021659-f00ee077-0c90-44f9-b7c9-64f446f7b69f.png)

**Comment by rvsp** [comment]
still mails are with broken image
