### ISSUE TITLE
Getting blank page if clicked on assigned query to comment 

### ISSUE THREAD

**Issue by lavishjain36** [zen-class/zen-platform#21]
![blankscreen](https://user-images.githubusercontent.com/26799843/129567754-734bc7ac-8af0-4b52-aec2-b0a4a71b0d6a.JPG)

**Comment by thecoffeedev** [comment]
@lavishjain36, May I know the Query number?
if the Query number is QN263, we have resolved and fixed it.
Please let us know as early as possible.

**Comment by lavishjain36** [comment]
it was due to delay in response .Later got resolved

**Comment by rvsp** [comment]
closed!
