### ISSUE TITLE
Query raising

### ISSUE THREAD

**Issue by lavishjain36** [zen-class/zen-platform#23]
![closedquery](https://user-images.githubusercontent.com/26799843/129569096-89bfab15-4a99-4221-9dd3-42a77cd34c7a.JPG)

Student should not be allowed to raise a new query if previous query is not closed at the student end.

**Comment by thecoffeedev** [comment]
@lavishjain36, As of now, Students can raise a query if he had replied to his open Queries ( to the mentors ) or he has no resolved Queries at the moment.
If there is a Query that is resolved, the student has to close it before creating a new Query.

Please let us know if you have any further suggestions else we can close this issue.

**Comment by rvsp** [comment]
@Varghese1987 / @thecoffeedev as we planned for the new design, am moving to done

**Comment by thecoffeedev** [comment]
@rvsp, I think the logic of @lavishjain36 is not coping up with our logic.
As per our logic, a Query should not be created if not replied to the mentor or have a resolved query right?
And that is already in LIVE.
but @lavishjain36 is saying students can only create a single query at a time.
@rvsp please verify with @lavishjain36.

**Comment by thecoffeedev** [comment]
The new design will have the same flow as of now @rvsp if not revised.
