### ISSUE TITLE
Additional session link issue

### ISSUE THREAD

**Issue by MohanCloud-stack** [zen-class/zen-platform#25]
Even though  i updated the session link in the additional session. Respective link is not enabled in the student login

**Comment by MohanCloud-stack** [comment]
![Screenshot (682)](https://user-images.githubusercontent.com/45478292/129838701-a84a292d-936f-47ef-9a62-a278eb87de12.png)
![Screenshot (681)](https://user-images.githubusercontent.com/45478292/129838709-9a1ee5b2-5bf1-487a-8649-35daab35e94c.png)

**Comment by thecoffeedev** [comment]
@MohanCloud-stack, we have tested and I have verified with the same credentials which you have. I can see the session link for additional session.
If my understanding of your question is wrong, please correct me!

**Comment by MohanCloud-stack** [comment]
Hi anand,

The above issue is fixed
