### ISSUE TITLE
Query From student for task submission

### ISSUE THREAD

**Issue by lavishjain36** [zen-class/zen-platform#31]
Task submit dropdown option for day 1,2,3,4 not showing.

**Comment by lavishjain36** [comment]
![WhatsApp Image 2021-08-20 at 12 58 49 PM](https://user-images.githubusercontent.com/26799843/130225411-28c07203-1728-4e19-b276-21cdee3878e9.jpeg)
Adding screenshot

**Comment by thecoffeedev** [comment]
@lavishjain36 The screenshot page will change when the user is converted to the main bootcamp.
if there is no task?, the dropdown will not occur.
