### ISSUE TITLE
Query from student

### ISSUE THREAD

**Issue by lavishjain36** [zen-class/zen-platform#33]
I HAve Submitted day 1 task on the same day of class yet it shows submitted on 23rd ?? Also Day 2 I have attended and the portal is still asking me to join.
Name:Joseph John Louis Paul
Email:josephjohnlouispaul@gmail.com

**Comment by thecoffeedev** [comment]
@lavishjain36 sry for the delay in reply, I hope the issue has been resolved earlier!
please verify so that we can close the issue.
